# Generated by Django 4.1.5 on 2023-01-05 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='basicapi.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.TextField(),
        ),
    ]
