# Generated by Django 4.1.5 on 2023-01-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapi', '0002_alter_book_author_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.TextField(max_length=100),
        ),
    ]
