# Generated by Django 4.1.5 on 2023-01-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapi', '0004_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.TextField(),
        ),
    ]
