# Generated by Django 4.1.5 on 2023-01-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapi', '0005_alter_book_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.TextField(),
        ),
    ]
